"use client";

import { Button } from "@/components/ui/button";
import { useState } from "react";
import { authStorage } from "@/lib/auth";
import { useRouter } from "next/navigation";

interface ConnectRazorpayButtonProps {
    className?: string;
    isConnected?: boolean;
}

export function ConnectRazorpayButton({ className, isConnected = false }: ConnectRazorpayButtonProps) {
    const [loading, setLoading] = useState(false);
    const router = useRouter();

    const handleConnect = () => {
        try {
            setLoading(true);
            const token = authStorage.getAccessToken();

            if (!token) {
                setLoading(false);
                router.push("/login?redirect=/dashboard/org/settings");
                return;
            }

            // Direct redirect to Razorpay OAuth URL
            // Note: In production, the state parameter should be dynamically generated by the backend
            // to securely link the OAuth callback to the correct organization
            const razorpayOAuthUrl = "https://auth.razorpay.com/authorize?response_type=code&client_id=Rtwbh49HVFeYwm&redirect_uri=https%3A%2F%2Fodooxspit-appointment-app.onrender.com%2Fauth%2Frazorpay%2Fcallback&scope=read_only&state=current_state"
            window.location.href = razorpayOAuthUrl;
        } finally {
            // Loading state will effectively stop once navigation happens
            setTimeout(() => setLoading(false), 1000);
        }
    };

    return (
        <Button onClick={handleConnect} className={className} disabled={loading}>
            {loading ? "Redirecting to Razorpay..." : isConnected ? "Reconnect Razorpay" : "Connect Razorpay"}
        </Button>
    );
}
